# SPDX-FileCopyrightText: 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Perform etcd installation tasks
  block:
    - name: Validate etcd configuration
      when: etcd_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install etcd
      when: etcd_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-etcd
    - install-all
    - install-etcd

- name: Perform etcd uninstallation tasks
  block:
    - name: Uninstall etcd
      when: not etcd_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-etcd
