# SPDX-FileCopyrightText: 2023 - 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "etcd_systemd_required_systemd_services_list_default", "new": "etcd_systemd_required_services_list_default" }
    - { "old": "etcd_systemd_required_systemd_services_list_auto", "new": "etcd_systemd_required_services_list_auto" }
    - { "old": "etcd_systemd_required_systemd_services_list_custom", "new": "etcd_systemd_required_services_list_custom" }

- name: Fail if required etcd settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item.name }}`).
  when: "item.when | bool and lookup('vars', item.name, default='') | string | length == 0"
  with_items:
    - { "name": "etcd_identifier", "when": true }
    - { "name": "etcd_uid", "when": true }
    - { "name": "etcd_gid", "when": true }
    - { "name": "etcd_container_network", "when": true }
    - { "name": "etcd_environment_variable_etcd_root_password", "when": "{{ not etcd_environment_variable_allow_none_authentication }}" }

- name: Fail if etcd logging level is invalid
  ansible.builtin.fail:
    msg: >-
      etcd_environment_variable_etcd_log_level must be 'debug', 'info', 'warn', 'error', 'panic', or 'fatal'
  when: "etcd_environment_variable_etcd_log_level not in ['debug', 'info', 'warn', 'error', 'panic', 'fatal']"
